# Generated by Django 3.2.4 on 2021-07-09 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_contoller', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
