# Generated by Django 3.2.4 on 2021-07-10 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_contoller', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='jwt_token',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
