# Generated by Django 3.2.4 on 2021-07-11 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_contoller', '0003_user_jwt_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='jwt_token',
        ),
    ]
